version: '3.8'

services:

  redis:
    image: redis:alpine

  web:
    build: .
    command: >
        sh -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               python manage.py runserver 0.0.0.0:8080"
    volumes:
        - .:/code
    ports:
        - "8080:8080"
    depends_on:
      - redis


  celery:
    build: .
    command: celery -A shop_system worker -l info
    volumes:
      - .:/code/
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-v#zs7&&7iq4il9e7q46++w!pyxlqm^0fac^1a4g53ha&ud9o#1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A shop_system beat -l info
    volumes:
      - .:/code/
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-v#zs7&&7iq4il9e7q46++w!pyxlqm^0fac^1a4g53ha&ud9o#1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    ports:
      - "80:8080"
    volumes:
      - ./doc:/usr/share/nginx/html/doc
    environment:
      API_URL: doc/openapi.yaml

volumes:
  static_value:
  media_value:

