# Generated by Django 3.2.9 on 2023-01-15 19:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='product name')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='price of product')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creation date')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('done', 'Done'), ('paid', 'Paid')], default='new', max_length=20)),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creation date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='order_processing.product', verbose_name='product of order')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creation date')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_order', to='order_processing.order', verbose_name='invoice of order')),
            ],
        ),
    ]
