# Generated by Django 3.2.9 on 2023-01-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_processing', '0002_alter_order_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creation date'),
        ),
    ]
