# Generated by Django 3.2.9 on 2023-01-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_processing', '0004_alter_order_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_activate',
            field=models.BooleanField(default=False),
        ),
    ]
